AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'

# For single-file applications, longer classes are acceptable
Metrics/ClassLength:
  Max: 200

# Allow longer methods for complex data processing
Metrics/MethodLength:
  Max: 20

# Allow higher complexity for filter logic
Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15
